# @param {string[]} env Environments
environments:
  - dev
  - uat
  - pro

# @param {object[]} tickets Environments
tickets:
  - id: ticket1
    title: title1
    body: body1
  - id: ticket2
    title: title2
    body: body3