apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/connector-verbose: "true"
    meta.helm.sh/release-namespace: krateo-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: pbi
  namespace: demo-system
spec:
  chart:
    url: https://github.com/AndreaTosti/krateo-v2-template-fireworksapp/releases/download/0.1.22/pbi-0.1.22.tgz
  deletionPolicy: Delete