<<<<<<< HEAD
apiVersion: composition.krateo.io/v0-1-23
=======
apiVersion: composition.krateo.io/v0-1-24
>>>>>>> e2a6c8d96f5aa000c3a962a8d6bea0a1a86ddbd9
kind: Pbi
metadata:
  annotations:
    krateo.io/connector-verbose: "true"
    meta.helm.sh/release-namespace: krateo-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: instance1
  namespace: demo-system
spec:
  environments:
    - dev
    - uat
    - pro
  tickets:
    - id: ticket1
      title: title1
      body: body1
    - id: ticket2
      title: title2
      body: body2