{{- if eq .Values.infra.env "dev" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.fullname" . }}
  labels:
    {{- include "fireworks-app.labels" . | nindent 4 }}
data:
  values: |
    { "env": "{{ .Values.infra.env }}"
    }

{{- end }}