{{- $chartname := include "fireworks-app.chart" $ -}}
{{- $ticketname := printf "%s-jira-ticket1" $chartname -}}
{{/*{{- $resource := lookup "v1" "ConfigMap" "demo-system" "$ticketname" -}}*/}}
{{- $resource := lookup "v1" "ConfigMap" "demo-system" "pbi-0.1.23-jira-ticket1" -}}
{{- if and $resource (eq $resource.data.status "done") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-pbi-pipeline
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  id: ""
  workspace-dev-id: ""
  workspace-uat-id: ""
  workspace-pro-id: ""
...
{{- end }}