<<<<<<< HEAD
{{- $chartname := include "fireworks-app.chart" $ -}}
{{- $ticketname := printf "%s-jira-ticket1" $chartname -}}
{{- $ticket := lookup "v1" "ConfigMap" "demo-system" $ticketname -}}
{{- if and $ticket (eq $ticket.data.status "done") }}
=======
{{- if and (include "fireworks-app.is-ticket1-solved" $) (include "fireworks-app.is-ticket2-solved" $) }}
>>>>>>> e2a6c8d96f5aa000c3a962a8d6bea0a1a86ddbd9
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-pbi-pipeline
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  id: ""
  workspace-dev-id: ""
  workspace-uat-id: ""
  workspace-pro-id: ""
...
{{- end }}