{{ $resource := lookup "v1" "ConfigMap" "demo-system" "pbi-0.1.22-jira-ticket1" }}
{{- if and $resource (eq $resource.data.status "done") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-pbi-pipeline
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  id: ""
  workspace-dev-id: ""
  workspace-uat-id: ""
  workspace-pro-id: ""
...
{{- end }}