{{- $chartname := include "fireworks-app.chart" $ -}}
{{- $ticketname := printf "%s-jira-ticket1" $chartname -}}
{{- $ticket := lookup "v1" "ConfigMap" "demo-system" $ticketname -}}
{{- if and $ticket (eq $ticket.data.status "done") }}
{{- range $environment := .Values.environments }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-pbi-workspace-{{ $environment }}
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  precondition-ticket1-status: ""
  precondition-ticket2-status: ""
  id: ""
  env: {{ $environment }}
{{- end }}
{{- end }}
...