{{- if and (include "fireworks-app.is-ticket1-solved" $) (include "fireworks-app.is-ticket2-solved" $) }}
{{- range $environment := .Values.environments }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-pbi-workspace-{{ $environment }}
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  precondition-ticket1-status: ""
  precondition-ticket2-status: ""
  id: ""
  env: {{ $environment }}
...
{{- end }}
{{- end }}