{{- $chartname := include "fireworks-app.chart" $ -}}
{{- $ticketname := printf "%s-jira-ticket1" $chartname -}}
{{- $ticket := lookup "v1" "ConfigMap" "demo-system" $ticketname -}}
{{- $status := (index ($ticket.data | default dict) "status" | default "") -}}
{{- if eq $status "done" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fireworks-app.chart" $ }}-pbi-pipeline
  namespace: demo-system
  labels:
    {{- include "fireworks-app.labels" $ | nindent 4 }}
data:
  id: ""
  workspace-dev-id: ""
  workspace-uat-id: ""
  workspace-pro-id: ""
...
{{- end }}