apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pbi
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io/v1
  resources:
  - crds
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch