{{- if .Values.infra.svc }}

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "fireworks-app.labels" . | nindent 4 }}
  name: {{ include "fireworks-app.fullname" . }}
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30089
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: krateo-bff
    app.kubernetes.io/name: krateo-bff
  sessionAffinity: None
  type: NodePort

{{- end }}